### ISSUE TITLE
From KKL

### ISSUE THREAD

**Issue by SimonHunag** [Sife-shuo/Sife-shuo.github.io#1]
你好：
       感谢你对开课啦的支持，你的项目让我们发现很多问题，并且得到了提升。除此发现你在这块的天赋，如果有机会，可以来我们公司对前端技术、后端架构、大数据与AI技术做一下开放性的交流。也能够在技术有不同能力的拓展。

**Comment by Sife-shuo** [comment]
太抱歉了（直到我中考后7.20才看见），我已经去了部分工具了，现在我写的那些东西访问不到了，我对工具对你们造成的影响深感抱歉
